<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Competition;
use App\Models\Category;
use App\Models\City;
use Illuminate\Support\Str;

class CompetitionSeeder extends Seeder
{
    public function run(): void
    {
        $categories = Category::where('type', 'competition')->pluck('id', 'name')->toArray();
        $city = City::first();
        $cityId = $city ? $city->id : null;

        $competitions = [
            [
                'name' => 'National Science & Innovation Olympiad 2026',
                'slug' => 'national-science-innovation-olympiad-2026',
                'code' => 'NSIO-2026',
                'category_name' => 'MAESTROMATH OLYMPIAD (MMO)',
                'description' => 'A premier national science contest designed to foster logical thinking, scientific inquiry, and innovative problem solving among school students.',
                'start_date' => '2026-10-15',
                'end_date' => '2026-10-18',
                'location' => 'IIT Bombay Campus & Online',
                'scope' => 'national',
                'organizer_name' => 'Sambhav National Science Foundation',
                'organizer_email' => 'nsio@sambhav.org',
                'organizer_phone' => '+91 98765 43210',
                'organizer_website' => 'https://nsio.sambhav.org',
                'rules' => "1. Students must belong to Grade 5-12.\n2. Round 1 is an online MCQ test (60 mins).\n3. Top 100 students advance to the Hands-on Experiment Round at IIT Bombay.",
                'prize' => "1st Prize: ₹50,000 + Trophy\n2nd Prize: ₹25,000 + Silver Medal\n3rd Prize: ₹10,000 + Bronze Medal\nParticipation Certificate for all candidates.",
                'terms_and_conditions' => 'Registration fees are non-refundable. Organizers decision on evaluation is final.',
                'registration_fee' => 250,
                'registration_deadline' => '2026-10-10',
                'apply_url' => 'https://nsio.sambhav.org/register',
                'eligibility_criteria' => 'Open to all students currently enrolled in Grade 5 to Grade 12.',
                'grade_min' => 5,
                'grade_max' => 12,
                'judging_criteria' => 'Accuracy (40%), Speed (30%), Problem Solving Approach (30%).',
                'status' => 'active',
            ],
            [
                'name' => 'IOQM (Indian Olympiad Qualifier in Mathematics)',
                'slug' => 'ioqm-indian-olympiad-qualifier-maths-2026',
                'code' => 'IOQM-2026',
                'category_name' => 'IOQM (Indian Olympiad Qualifier in Maths)',
                'description' => 'The official first stage qualifier for the International Mathematical Olympiad (IMO). Tests advanced problem-solving, number theory, geometry, and combinatorics.',
                'start_date' => '2026-11-05',
                'end_date' => '2026-11-05',
                'location' => 'Designated Exam Centers Nationwide',
                'scope' => 'national',
                'organizer_name' => 'Mathematics Teachers Association (India)',
                'organizer_email' => 'support@mtai.org.in',
                'organizer_phone' => '+91 22 2557 5622',
                'organizer_website' => 'https://mtai.org.in',
                'rules' => "1. OMR-based offline exam.\n2. 30 questions carrying 2, 3, and 5 marks.\n3. No electronic devices or calculators allowed.",
                'prize' => "Qualification certificate for RMO/INMO round + Gold/Silver/Bronze Certificates.",
                'terms_and_conditions' => 'Students must carry valid school ID and admit card to the exam hall.',
                'registration_fee' => 300,
                'registration_deadline' => '2026-10-20',
                'apply_url' => 'https://mtai.org.in/ioqm-register',
                'eligibility_criteria' => 'Students born after September 1, 2006, enrolled in Grade 8 to 12.',
                'grade_min' => 8,
                'grade_max' => 12,
                'judging_criteria' => 'Objective marks scored in the 30-question paper.',
                'status' => 'active',
            ],
            [
                'name' => 'ISB Spelling Bee International 2026',
                'slug' => 'isb-spelling-bee-international-2026',
                'code' => 'ISB-SPELL-2026',
                'category_name' => 'ISB Spelling Bee International',
                'description' => 'An international spelling competition testing vocabulary, etymology, word origins, and pronunciation precision across multiple levels.',
                'start_date' => '2026-10-25',
                'end_date' => '2026-10-26',
                'location' => 'Online Live Proctored Platform',
                'scope' => 'international',
                'organizer_name' => 'International Spelling Bee Association',
                'organizer_email' => 'info@isbbee.org',
                'organizer_phone' => '+91 91234 56789',
                'organizer_website' => 'https://isbbee.org',
                'rules' => "1. Oral & Written spelling rounds.\n2. Participants are categorized into Group A (Grades 1-3), Group B (Grades 4-6), and Group C (Grades 7-10).",
                'prize' => "Winner: \$1,000 USD + Championship Shield\nRunners Up: \$500 USD + Medals\nTop 50 receive Merit Certificates.",
                'terms_and_conditions' => 'Stable internet connection and camera required for online proctoring.',
                'registration_fee' => 500,
                'registration_deadline' => '2026-10-15',
                'apply_url' => null,
                'eligibility_criteria' => 'Open to students in Grades 1 to 10 from all recognized schools.',
                'grade_min' => 1,
                'grade_max' => 10,
                'judging_criteria' => 'Spelling accuracy, speed of response, and word origin knowledge.',
                'status' => 'active',
            ],
            [
                'name' => "Bhavan's Munshi Memorial Inter-School Debate",
                'slug' => 'bhavans-munshi-memorial-inter-school-debate',
                'code' => 'BMMD-2026',
                'category_name' => "Bhavan's Munshi Memorial Inter-School Debate",
                'description' => 'Prestigious annual debate tournament inviting top school debaters to argue contemporary socio-economic, environmental, and technological topics.',
                'start_date' => '2026-11-12',
                'end_date' => '2026-11-13',
                'location' => "Bharatiya Vidya Bhavan Auditorium, Mumbai",
                'scope' => 'state',
                'organizer_name' => 'Bharatiya Vidya Bhavan',
                'organizer_email' => 'debate@bhavans.ac.in',
                'organizer_phone' => '+91 22 2363 1261',
                'organizer_website' => 'https://bhavans.ac.in',
                'rules' => "1. Team of 2 speakers (One FOR, One AGAINST).\n2. Time allotted: 3 minutes per speaker + 1 minute interjection.\n3. Parliamentary debate rules apply.",
                'prize' => "Munshi Running Trophy + ₹20,000 Cash Prize for Best Team.\nBest Speaker Trophy + ₹5,000.",
                'terms_and_conditions' => 'Maximum 2 teams permitted per school institution.',
                'registration_fee' => 0,
                'registration_deadline' => '2026-11-01',
                'apply_url' => 'https://bhavans.ac.in/debate-registration',
                'eligibility_criteria' => 'Students from Grade 9 to Grade 12.',
                'grade_min' => 9,
                'grade_max' => 12,
                'judging_criteria' => 'Content & Substance (40%), Delivery & Diction (30%), Rebuttal (30%).',
                'status' => 'active',
            ],
            [
                'name' => 'Inter-School AI & Robotics Hackathon 2026',
                'slug' => 'inter-school-ai-robotics-hackathon-2026',
                'code' => 'AIRH-2026',
                'category_name' => 'Co-Curricular Activities & Sports',
                'description' => 'A 24-hour hands-on coding and robotics challenge where students build working prototypes using Arduino, Raspberry Pi, and Python AI models.',
                'start_date' => '2026-11-20',
                'end_date' => '2026-11-21',
                'location' => 'Tech Park Convention Hall & Remote',
                'scope' => 'national',
                'organizer_name' => 'Sambhav Robotics & Tech Club',
                'organizer_email' => 'hackathon@sambhav.org',
                'organizer_phone' => '+91 99887 76655',
                'organizer_website' => 'https://hackathon.sambhav.org',
                'rules' => "1. Teams of 2 to 4 students.\n2. Open source hardware & libraries allowed.\n3. Final pitch demo (5 mins) in front of tech industry judges.",
                'prize' => "Grand Prize: ₹1,00,000 Seed Incubator Fund + Laptops.\nRunner Up: 3D Printers + Smart Robot Kits.",
                'terms_and_conditions' => 'All code created during hackathon must be uploaded to GitHub repository.',
                'registration_fee' => 0,
                'registration_deadline' => '2026-11-10',
                'apply_url' => null,
                'eligibility_criteria' => 'Grades 6 to 12.',
                'grade_min' => 6,
                'grade_max' => 12,
                'judging_criteria' => 'Innovation (35%), Technical Complexity (30%), Prototype Functionality (25%), Presentation (10%).',
                'status' => 'active',
            ],
            [
                'name' => 'National Financial Literacy Quest 2026',
                'slug' => 'national-financial-literacy-quest-2026',
                'code' => 'NFLQ-2026',
                'category_name' => 'FIN-EDU QUEST (Financial Literacy)',
                'description' => 'Empowering young minds with essential money skills, stock market basics, budgeting, smart saving, and entrepreneurship fundamentals.',
                'start_date' => '2026-10-30',
                'end_date' => '2026-10-30',
                'location' => 'Online Platform',
                'scope' => 'national',
                'organizer_name' => 'National Financial Education Foundation',
                'organizer_email' => 'finquest@nfef.org',
                'organizer_phone' => '+91 80 4567 8900',
                'organizer_website' => 'https://nfef.org',
                'rules' => "1. 45-minute interactive quiz & case study evaluation.\n2. Instant score report and financial badge generation.",
                'prize' => "Scholarship Cash Vouchers up to ₹15,000 for top 10 rankers.",
                'terms_and_conditions' => 'Free registration for all CBSE/ICSE/State Board students.',
                'registration_fee' => 0,
                'registration_deadline' => '2026-10-28',
                'apply_url' => 'https://nfef.org/quest-signup',
                'eligibility_criteria' => 'Students in Grades 7 to 12.',
                'grade_min' => 7,
                'grade_max' => 12,
                'judging_criteria' => 'Accuracy and speed in solving practical financial scenario problems.',
                'status' => 'active',
            ],
            [
                'name' => 'Sportathon 2026 (Basketball & Table Tennis)',
                'slug' => 'sportathon-2026-basketball-table-tennis',
                'code' => 'SPRT-2026',
                'category_name' => 'Sportathon (Basketball, Football, Table Tennis)',
                'description' => 'Action-packed inter-school sports championship featuring 3v3 Basketball knockout tournament and Singles/Doubles Table Tennis matches.',
                'start_date' => '2026-12-01',
                'end_date' => '2026-12-03',
                'location' => 'District Sports Complex Stadium',
                'scope' => 'regional',
                'organizer_name' => 'District School Sports Association',
                'organizer_email' => 'sports@dssa.org',
                'organizer_phone' => '+91 94444 33333',
                'organizer_website' => 'https://dssa.org',
                'rules' => "1. Official FIBA 3v3 rules for Basketball.\n2. ITTF rules for Table Tennis.\n3. School sports jersey mandatory.",
                'prize' => "Trophies, Gold/Silver Medals, and Sports Equipment vouchers for winning teams.",
                'terms_and_conditions' => 'Medical fitness certificate signed by school doctor required.',
                'registration_fee' => 400,
                'registration_deadline' => '2026-11-20',
                'apply_url' => null,
                'eligibility_criteria' => 'Under-14 and Under-17 categories for boys and girls.',
                'grade_min' => 5,
                'grade_max' => 12,
                'judging_criteria' => 'Tournament bracket knockout scoring system.',
                'status' => 'active',
            ],
            [
                'name' => 'THE NEXT VOICE (Poetry & Storytelling)',
                'slug' => 'the-next-voice-poetry-storytelling-2026',
                'code' => 'TNV-2026',
                'category_name' => 'THE NEXT VOICE (Spoken Word/Poetry/Storytelling)',
                'description' => 'A creative platform for young poets, storytellers, and spoken word artists to express their voices on themes of hope, environment, and humanity.',
                'start_date' => '2026-11-15',
                'end_date' => '2026-11-16',
                'location' => 'City Cultural Center & YouTube Live',
                'scope' => 'national',
                'organizer_name' => 'Literary & Performing Arts Academy',
                'organizer_email' => 'tnv@literaryacademy.org',
                'organizer_phone' => '+91 97777 66666',
                'organizer_website' => 'https://literaryacademy.org',
                'rules' => "1. Original compositions only (English or Hindi).\n2. Time limit: 4 minutes performance per participant.",
                'prize' => "Publishing contract for top 10 poems in annual anthology + ₹15,000 Cash Prize.",
                'terms_and_conditions' => 'Submissions must be original and unpublished.',
                'registration_fee' => 150,
                'registration_deadline' => '2026-11-05',
                'apply_url' => 'https://literaryacademy.org/tnv-submit',
                'eligibility_criteria' => 'Students from Grade 4 to 12.',
                'grade_min' => 4,
                'grade_max' => 12,
                'judging_criteria' => 'Expression & Emotion (30%), Originality (30%), Voice Modulation (20%), Stage Presence (20%).',
                'status' => 'active',
            ]
        ];

        foreach ($competitions as $data) {
            $categoryName = $data['category_name'];
            unset($data['category_name']);

            $categoryId = $categories[$categoryName] ?? (reset($categories) ?: null);

            Competition::updateOrCreate(
                ['slug' => $data['slug']],
                array_merge($data, [
                    'category_id' => $categoryId,
                    'city_id' => $cityId,
                ])
            );
        }

        $this->command->info('Successfully seeded ' . count($competitions) . ' competitions!');
    }
}
